- alias: Установка счетчика холодной воды
  trigger:
  - platform: state
    entity_id: input_number.water_input1
  action:
  - service: modbus.write_register
    data:
      hub: hub1
      unit: 1
      address: 0
    data_template:
      value: '{{ states.input_number.water_input1.state|int }}'
  id: c7112dd1ba904d78923114dcbcec270a
- alias: Установка таймера мультиварки
  trigger:
  - platform: state
    entity_id: input_datetime.time_setup_ready_sky
  action:
  - service: ready4sky.set_timer
    entity_id: water_heater.cooker_rfs_kmc001
    data_template:
      hours: '{{ state_attr( "input_datetime.time_setup_ready_sky" , "hour") }}'
      minutes: '{{ state_attr( "input_datetime.time_setup_ready_sky", "minute") }}'
  id: 0cff7590445f402798b0bdfbf279ae19
- id: '1607361473778'
  alias: Мультиварка оповещения
  description: ''
  trigger:
  - platform: state
    entity_id: water_heater.cooker_rfs_kmc001
  - platform: state
    entity_id: sensor.status_rfs_kmc001
    attribute: sync
    to: STARTING PROGRAM
  - platform: state
    entity_id: sensor.status_rfs_kmc001
    to: HEAT
  condition: []
  action:
  - service: notify.mobile_app_redmi_note_8t
    data:
      title: Мультиварка
      message: 'Установлена программа: {{ states.water_heater.cooker_rfs_kmc001.state
        }}, режим {{ states.sensor.status_rfs_kmc001.state }}'
      data:
        tag: cook
        icon_url: /local/kitchen/multicook.png
        channel: Cook
  - service: notify.push
    data:
      title: Мультиварка
      message: 'Установлена программа: {{ states.water_heater.cooker_rfs_kmc001.state
        }}, режим {{ states.sensor.status_rfs_kmc001.state }}'
      data:
        icon: /local/kitchen/multicook.png
        tag: cook
  mode: single
- id: '1607589205051'
  alias: Проверка утечки воды
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.kholodnaia_voda
  condition:
  - condition: device
    device_id: 2cd2716e57fc81bbdb0d2e77f08a6115
    domain: device_tracker
    entity_id: device_tracker.e0_cc_f8_99_59_d9
    type: is_not_home
  action:
  - service: notify.push
    data:
      message: Утечка воды, у нас потоп, мы все утонем!
      data:
        ttl: 86400
        icon: /local/alerts/water_alert.jpg?
        priority: high
  - service: notify.mobile_app_redmi_note_8t
    data:
      message: Утечка воды, у нас потоп, мы все утонем!
      data:
        ttl: 86400
        priority: high
        channel: Alert
        icon_url: /local/alerts/water_alert.jpg
  mode: single
- id: '1607891415622'
  alias: Оповещение о температуре в комнате
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.temperatura_v_komnate
    below: '20'
  condition: []
  action:
  - service: notify.mobile_app_redmi_note_8t
    data:
      message: Температура в комнате меньше {{ states.sensor.temperatura_v_komnate.state}}
        градусов.
      data:
        channel: Alert
  mode: single
- id: '1614508576843'
  alias: Включить свет в зоне home
  description: Включить свет когда подхожу к дому
  trigger:
  - platform: state
    entity_id: device_tracker.e0_cc_f8_99_59_d9
    from: not_home
    to: home
  condition:
  - condition: device
    device_id: 2cd2716e57fc81bbdb0d2e77f08a6115
    domain: device_tracker
    entity_id: device_tracker.e0_cc_f8_99_59_d9
    type: is_home
  action:
  - service: switch.turn_on
    data: {}
    entity_id: group.kitchen
  mode: single
- id: '1614508874323'
  alias: Выключить свет
  description: Выключить свет при покидании зоны home
  trigger:
  - platform: state
    entity_id: device_tracker.e0_cc_f8_99_59_d9
    from: home
    to: not_home
  condition:
  - condition: device
    device_id: 2cd2716e57fc81bbdb0d2e77f08a6115
    domain: device_tracker
    entity_id: device_tracker.e0_cc_f8_99_59_d9
    type: is_not_home
  action:
  - service: switch.turn_off
    data: {}
    entity_id: group.left_line
  - service: switch.turn_off
    data: {}
    entity_id: group.right_line
  mode: single
- id: '1614511616822'
  alias: Будильник
  description: ''
  trigger:
  - platform: time
    at: input_datetime.budilnik
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: switch.turn_on
    data: {}
    entity_id: group.kitchen
  mode: single
- id: '1619043497285'
  alias: Сброс клапана холодной воды
  description: Ежедневное перекрытие шарового клапана холодной воды
  trigger:
  - platform: time_pattern
    hours: '9'
    seconds: '0'
    minutes: '0'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.klapan_kholodnoi_vody
  - delay: '30'
  - service: switch.turn_on
    data: {}
    entity_id: switch.klapan_kholodnoi_vody
  mode: single
